---
name: Arduino_CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@stable-1.x
        env:
          CUSTOM_INIT_SCRIPT: install_dependencies.sh
